### ISSUE TITLE
Fix for private server?

### ISSUE THREAD

**Issue by seathasky** [Zero1UP/FinalFantasyXIRichPresence#1]
Hi there! Lovely fix for RP and XI. Unfortunately doesn't seem to work on private servers.
Would there a way to make this happen?

![image](https://user-images.githubusercontent.com/17598024/179505837-aa649e1a-9d3b-4396-af53-6ad405d7f886.png)

**Comment by Zero1UP** [comment]
> Hi there! Lovely fix for RP and XI. Unfortunately doesn't seem to work on private servers. Would there a way to make this happen?
> 
> ![image](https://user-images.githubusercontent.com/17598024/179505837-aa649e1a-9d3b-4396-af53-6ad405d7f886.png)

You'd have to update the offsets starting here:
https://github.com/Zero1UP/FinalFantasyXIRichPresence/blob/ac33a5a09221852c10b89615bd946afe93d30070/FinalFantasyXIRichPresence/frm_Main.cs#L88

**Comment by seathasky** [comment]
What? haha. (Not a programmer)

**Comment by Zero1UP** [comment]
> What? haha. (Not a programmer)

The program reads the game's memory to pull out that information so you'd need to use something like cheat engine to find the address offsets for the fields that the program displays. The link I posted takes you to the bit of the code where the offsets are.

I would imagine things like the Job IDs and Map IDs are probably all the same so the only thing that would need to be updated is that.

**Comment by seathasky** [comment]
> 

Way out of my area of expertise I suppose. Probably just take the loss. Thanks anyways.

**Comment by Zero1UP** [comment]
> > 
> 
> Way out of my area of expertise I suppose. Probably just take the loss. Thanks anyways.

What private server is it? It's something I could probably look into.

**Comment by seathasky** [comment]
https://tabularasaxi.com/ specifically i've been messing around on, but I also play on https://edenxi.com/ and https://www.wingsxi.com/wings/. These are basically some of the new or popular pservers atm for the game. I appreciate the help! 

Let me know if you want me to do any testing if you figure it out!

**Comment by Zero1UP** [comment]
> https://tabularasaxi.com/ specifically i've been messing around on, but I also play on https://edenxi.com/ and https://www.wingsxi.com/wings/. These are basically some of the new or popular pservers atm for the game. I appreciate the help!
> 
> Let me know if you want me to do any testing if you figure it out!

Been a few years but I've gotten around to redoing this so this is less of an issue going forward. The latest update (1.2.0) has the data collection as an addon for windower. The program will then read the output and display that to discord.

https://github.com/Zero1UP/FinalFantasyXIRichPresence/releases/tag/v1.2.0
